[package]
name = "crypteia"
version = "1.0.0"
edition = "2021"

[[bin]]
name = "crypteia"

[lib]
name = "crypteia"
crate_type = ["cdylib"]

[dependencies]
# bin
anyhow = "1.0.57"
tokio = { version = "1.19.2", features = ["full"] }
futures = { version = "0.3.21" }
aws-config = "0.14.0"
aws-sdk-ssm = "0.14.0"
lambda-extension = "0.5.0"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
# lib
redhook = "2.0"
libc = "0.2.126"
lazy_static = "1.4.0"
# both
serde_json = "1.0.81"

[profile.release]
strip = true
